import { Request, Response } from "express";
import { ThrowError } from "../utils/ErrorUtil";

export const placeOrder = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const getAllOrders = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const getMyOrders = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const updateOrderStatus = async (
  request: Request,
  response: Response
) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};
