import { Request, Response } from "express";
import { ThrowError } from "../utils/ErrorUtil";

export const createProduct = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const updateProduct = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const getAllProducts = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const getProduct = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const deleteProduct = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};

export const getAllProductWithCatagoryId = async (request: Request, response: Response) => {
  try {
  } catch (error: any) {
    return ThrowError(response, error);
  }
};
